- name: configure {{ component }} server #component == backend
  hosts: localhost
  become: yes #remote server
  vars_files:
    - "variables-{{ environment }}.yaml"  #environment == dev
   #ansible server
  roles:
    - "{{ component }}"